### ISSUE TITLE
Cannot use umsg-gen to generate umsg_lib

### ISSUE THREAD

**Issue by Jaddu-jd** [amcolex/umsg#5]
Hi, 

So I found out about the umsg and would like to add it my project which is running in NuttX.

I was trying to generate the library using the .json topic file, same one in the examples to understand how this works.
But I am getting the output "No Files Found" error, even when the files exist in the folder.

Any idea what could be the reason, or what I am doing wrong?\

Thanks
Jd

**Comment by amcolex** [comment]
Hi @Jaddu-jd What command are you running exactly? What system are you running on?

**Comment by cptshirty** [comment]
Hi @amcolex, @Jaddu-jd  I had the same issue and solved it, i believe that there is a typo at umsg_gen.py:30 (there is a '\' instead of '/' in the string. Replacing it solved the issue for me. I would create a pull request, but it feels like a bit of a overkill for that kind of change.
